### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by mpbomil** [Ultimaker/cura-build#16]
I've downloaded the dependencies for windows stated in https://github.com/Ultimaker/cura-build#windows but I haven't figured out yet how to build it. 
Is there anyone that could help me out?

So far I've tried downloading the Cura Repository, replacing the CMakeLists with the one from cura-build and ran it with the mingw compiler, then I ran the makefile in the build folder with mingw32-make in CMD:
``` 
C:\Users\Mesut\Desktop\Cura-e4de852fd13cd7a95b8e087961e4f87635146567\build>mingw32-make -f C:\Users\Mesut\Desktop\Cura-e4de852fd13cd7a95b8e087961e4f87635146567\build\Makefile
Scanning dependencies of target Protobuf
[  1%] Creating directories for 'Protobuf'
[  2%] Performing download step (git clone) for 'Protobuf'
Cloning into 'Protobuf'...
Checking out files: 100% (682/682), done.
Your branch is up-to-date with 'origin/master'.
Already on 'master'
[  3%] No patch step for 'Protobuf'
[  4%] Performing update step for 'Protobuf'
Current branch master is up to date.
[  5%] Performing configure step for 'Protobuf'
-- The C compiler identification is GNU 4.8.1
-- The CXX compiler identification is GNU 4.8.1
-- Check for working C compiler: C:/MinGW/bin/gcc.exe
-- Check for working C compiler: C:/MinGW/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/MinGW/bin/g++.exe
-- Check for working CXX compiler: C:/MinGW/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/Mesut/Desktop/Cura-e4de852fd13cd7a95b8e087961e4f87635146567/build/Protobuf-prefix/src/Protobuf-build
[  6%] Performing build step for 'Protobuf'
Scanning dependencies of target libprotoc
[  0%] Building CXX object CMakeFiles/libprotoc.dir/src/google/protobuf/compiler/code_generator.cc.obj
[  1%] Building CXX object CMakeFiles/libprotoc.dir/src/google/protobuf/compiler/command_line_interface.cc.obj
[  2%] Building CXX object CMakeFiles/libprotoc.dir/src/google/protobuf/compiler/plugin.cc.obj
[  3%] Building CXX object CMakeFiles/libprotoc.dir/src/google/protobuf/compiler/plugin.pb.cc.obj
In file included from c:\mingw\lib\gcc\mingw32\4.8.1\include\c++\cmath:44:0,
                 from c:\mingw\lib\gcc\mingw32\4.8.1\include\c++\random:38,
                 from c:\mingw\lib\gcc\mingw32\4.8.1\include\c++\bits\stl_algo.h:65,
                 from c:\mingw\lib\gcc\mingw32\4.8.1\include\c++\algorithm:62,
                 from C:\Users\Mesut\Desktop\Cura-e4de852fd13cd7a95b8e087961e4f87635146567\build\Protobuf-prefix\src\Protobuf\src\google\protobuf\compiler\plugin.pb.cc:7:
c:\mingw\include\math.h: In function 'float hypotf(float, float)':
c:\mingw\include\math.h:635:30: error: '_hypot' was not declared in this scope
 { return (float)(_hypot (x, y)); }
                              ^
CMakeFiles\libprotoc.dir\build.make:137: recipe for target 'CMakeFiles/libprotoc.dir/src/google/protobuf/compiler/plugin.pb.cc.obj' failed
mingw32-make[5]: *** [CMakeFiles/libprotoc.dir/src/google/protobuf/compiler/plugin.pb.cc.obj] Error 1
CMakeFiles\Makefile2:66: recipe for target 'CMakeFiles/libprotoc.dir/all' failed
mingw32-make[4]: *** [CMakeFiles/libprotoc.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
mingw32-make[3]: *** [all] Error 2
CMakeFiles\Protobuf.dir\build.make:109: recipe for target 'Protobuf-prefix/src/Protobuf-stamp/Protobuf-build' failed
mingw32-make[2]: *** [Protobuf-prefix/src/Protobuf-stamp/Protobuf-build] Error 2
CMakeFiles\Makefile2:216: recipe for target 'CMakeFiles/Protobuf.dir/all' failed
mingw32-make[1]: *** [CMakeFiles/Protobuf.dir/all] Error 2
C:\Users\Mesut\Desktop\Cura-e4de852fd13cd7a95b8e087961e4f87635146567\build\Makefile:104: recipe for target 'all' failed
mingw32-make: *** [all] Error 2
```

**Comment by peteruithoven** [comment]
Maybe the required commands could be added to the Readme, like OS X?

**Comment by Ghostkeeper** [comment]
It seems this is a [bug in MinGW](http://ehc.ac/p/mingw/bugs/2250/). It has been fixed in bleeding-edge builds but those are not stable yet. It's strange that we didn't encounter this problem ourselves, since we target the same version of MinGW I think.

A workaround would be to include the option -D__NO_INLINE__ in the compiler options, according to g-truc/glm#300. Let's hope the MinGW developers can get that fix into a release build quickly, because this error is in Protobuf.

**Comment by awhiemstra** [comment]
@mpbomil I have been working on building on Windows, but it is not yet complete. Once I have everything working I will make sure to update the build instructions.

In regards to the specific error, as @Ghostkeeper mentions, it is a bug in MinGW. The best results so far are with MinGW 4.9.1 as that is also being used on Qt's CI system to test Windows build of Qt. I have plans to require 4.9.1 specifically as there are several issues building Qt using a newer MinGW.

**Comment by teddyorkie** [comment]
I have this exact issue trying to build Cura. Still don't know where to put to -D__NO_INLINE__.
I'm also trying to build CuraEngine from msys console, and I think I have a similar problem. Here's the log
```
[  2%] Building CXX object CMakeFiles/clipper.dir/libs/clipper/clipper.cpp.obj
[  5%] Linking CXX static library libclipper.a
[  5%] Built target clipper
[  7%] Running C++ protocol buffer compiler on Cura.proto
Scanning dependencies of target CuraEngine
[ 10%] Building CXX object CMakeFiles/CuraEngine.dir/src/bridge.cpp.obj
[ 12%] Building CXX object CMakeFiles/CuraEngine.dir/src/comb.cpp.obj
[ 15%] Building CXX object CMakeFiles/CuraEngine.dir/src/commandSocket.cpp.obj
[ 17%] Building CXX object CMakeFiles/CuraEngine.dir/src/FffGcodeWriter.cpp.obj
[ 20%] Building CXX object CMakeFiles/CuraEngine.dir/src/FffPolygonGenerator.cpp.obj
[ 22%] Building CXX object CMakeFiles/CuraEngine.dir/src/FffProcessor.cpp.obj
[ 25%] Building CXX object CMakeFiles/CuraEngine.dir/src/gcodeExport.cpp.obj
d:/CuraEngine/src/gcodeExport.cpp: In member function 'void cura::GCodeExport::w
riteMove(int, int, int, double, double)':
d:/CuraEngine/src/gcodeExport.cpp:285:44: error: 'isinf' was not declared in thi
s scope
                 if (isinf(currentPosition.z))
                                            ^
d:/CuraEngine/src/gcodeExport.cpp:285:44: note: suggested alternatives:
In file included from d:/CuraEngine/src/gcodeExport.cpp:4:0:
d:/MinGW/mingw32/i686-w64-mingw32/include/c++/cmath:614:5: note:   'std::isinf'
     isinf(_Tp __x)
     ^
d:/MinGW/mingw32/i686-w64-mingw32/include/c++/cmath:614:5: note:   'std::isinf'
make[2]: *** [CMakeFiles/CuraEngine.dir/src/gcodeExport.cpp.obj] Error 1
make[1]: *** [CMakeFiles/CuraEngine.dir/all] Error 2
make: *** [all] Error 2
```
Can anyone help>?

**Comment by awhiemstra** [comment]
This is actually a coding error in the engine code, introduced by Ultimaker/CuraEngine@fb950227 . @BagelOrb this one is yours.

**Comment by Ghostkeeper** [comment]
It was fixed in Ultimaker/CuraEngine@c5be07212e1d46f5ddcb3e7025b184f1768231a2.
